syntax = "proto3";
package gantry.leaderboard.v1;

service LeaderboardService {
    rpc UpdateLeaderboard(UpdateLeaderboardRequest) returns (UpdateLeaderboardResponse);
}

enum WinningCondition {
    WINNING_CONDITION_UNSPECIFIED = 0;
    WINNING_CONDITION_KNOCKOUT = 1;
    WINNING_CONDITION_QUIT = 2;
    WINNING_CONDITION_TIMEOUT = 3;
}
message UpdateLeaderboardRequest {
    string player_1_id = 1;
    string player_2_id = 2;
    int32 player_1_score = 3;
    int32 player_2_score = 4;
    string winner = 5;
    WinningCondition winning_condition = 6;
    string match_id = 7;
}

message UpdateLeaderboardResponse {
    WinningCondition winning_condition = 1;
    int32 player_1_score = 2;
    int32 player_2_score = 3;
}
